version: '3.8'

services:
  # База данных
  chromadb:
    image: chromadb/chroma:latest
    ports:
      - "8000:8000"
    volumes:
      - ./data:/chroma/chroma
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/api/v1/heartbeat"]
      interval: 30s
      timeout: 10s
      retries: 3

  # AI сервис
  ai-assistant:
    build: .
    ports:
      - "7861:7861"
    volumes:
      - ./models:/app/models
    depends_on:
      - chromadb
    environment:
      - CHROMA_HOST=chromadb
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:7861"]
      interval: 30s
      timeout: 10s
      retries: 3

  # Мониторинг
  prometheus:
    image: prom/prometheus:latest
    ports:
      - "9090:9090"
    volumes:
      - ./monitoring/prometheus.yml:/etc/prometheus/prometheus.yml
    depends_on:
      - ai-assistant
      - chromadb

  # Дашборд
  grafana:
    image: grafana/grafana:latest
    ports:
      - "3000:3000"
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin
    volumes:
      - grafana-storage:/var/lib/grafana
    depends_on:
      - prometheus

volumes:
  grafana-storage:
